[INFO   ] Logger: Record log in /storage/emulated/0/pythonscripts/DragonWars/.kivy/logs/kivy_19-04-08_23.txt
[INFO   ] Kivy: v1.11.0.dev0, git-8b6af30, 20190320
[INFO   ] Python: v3.7.2 (default, Mar 20 2019, 14:25:26) 
[GCC 8.2.0]
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Audio: Providers: audio_sdl2 (audio_ffpyplayer ignored)
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/pythonscripts/DragonWars/dragonwars_anim8.py", line 336, in <module>
[WARNING] stderr:     
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 368, in load_string
[WARNING] stderr:     parser = Parser(content=string, filename=fn)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/parser.py", line 392, in __init__
[WARNING] stderr:     self.parse(content)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/parser.py", line 501, in parse
[WARNING] stderr:     objects, remaining_lines = self.parse_level(0, lines)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/parser.py", line 648, in parse_level
[WARNING] stderr:     level + 2, lines[i:], spaces)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/parser.py", line 575, in parse_level
[WARNING] stderr:     'Invalid data after declaration')
[WARNING] stderr: kivy.lang.parser.ParserException: Parser: File "<inline>", line 125:
[WARNING] stderr: ...
[WARNING] stderr:     123:<Fight_Screen>:
[WARNING] stderr:     124:    canvas.before:
[WARNING] stderr: >>  125:        id: fight_canvas
[WARNING] stderr:     126:        Rectangle:
[WARNING] stderr:     127:            pos: self.pos
[WARNING] stderr: ...
[WARNING] stderr: Invalid data after declaration
