[INFO   ] Logger: Record log in /storage/emulated/0/pythonscripts/DragonWars/.kivy/logs/kivy_19-04-08_58.txt
[INFO   ] Kivy: v1.11.0.dev0, git-8b6af30, 20190320
[INFO   ] Python: v3.7.2 (default, Mar 20 2019, 14:25:26) 
[GCC 8.2.0]
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Audio: Providers: audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 V@269.0 (GIT@3cacbab, I3843e1d0c8) (Date:04/05/18)'>
[INFO   ] GL: OpenGL vendor <b'Qualcomm'>
[INFO   ] GL: OpenGL renderer <b'Adreno (TM) 505'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] GL: Unpack subimage support is not available
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "<string>", line 15, in <module>
[WARNING] stderr: NameError: name 'Screen_Manager' is not defined
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 615, in _apply_rule
[WARNING] stderr:     rctx['ids'])
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 254, in create_handler
[WARNING] stderr:     cause=tb)
[WARNING] stderr: kivy.lang.builder.BuilderException: Parser: File "<inline>", line 15:
[WARNING] stderr: ...
[WARNING] stderr:      13:        id: begin_screen
[WARNING] stderr:      14:        name: 'begin_screen'
[WARNING] stderr: >>   15:        manager: Screen_Manager
[WARNING] stderr:      16:    Fight_Screen:
[WARNING] stderr:      17:        id: fight_screen
[WARNING] stderr: ...
[WARNING] stderr: NameError: name 'Screen_Manager' is not defined
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "<string>", line 15, in <module>
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/pythonscripts/DragonWars/dragonwars_anim9.py", line 910, in <module>
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/app.py", line 800, in run
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "/storage/emulated/0/pythonscripts/DragonWars/dragonwars_anim9.py", line 889, in build
[WARNING] stderr:     
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/uix/screenmanager.py", line 969, in __init__
[WARNING] stderr:     super(ScreenManager, self).__init__(**kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
[WARNING] stderr:     super(FloatLayout, self).__init__(**kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
[WARNING] stderr:     super(Layout, self).__init__(**kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/uix/widget.py", line 348, in __init__
[WARNING] stderr:     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 469, in apply
[WARNING] stderr:     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 630, in _apply_rule
[WARNING] stderr:     e), cause=tb)
[WARNING] stderr: kivy.lang.builder.BuilderException: Parser: File "<inline>", line 15:
[WARNING] stderr: ...
[WARNING] stderr:      13:        id: begin_screen
[WARNING] stderr:      14:        name: 'begin_screen'
[WARNING] stderr: >>   15:        manager: Screen_Manager
[WARNING] stderr:      16:    Fight_Screen:
[WARNING] stderr:      17:        id: fight_screen
[WARNING] stderr: ...
[WARNING] stderr: BuilderException: Parser: File "<inline>", line 15:
[WARNING] stderr: ...
[WARNING] stderr:      13:        id: begin_screen
[WARNING] stderr:      14:        name: 'begin_screen'
[WARNING] stderr: >>   15:        manager: Screen_Manager
[WARNING] stderr:      16:    Fight_Screen:
[WARNING] stderr:      17:        id: fight_screen
[WARNING] stderr: ...
[WARNING] stderr: NameError: name 'Screen_Manager' is not defined
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "<string>", line 15, in <module>
[WARNING] stderr: 
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 615, in _apply_rule
[WARNING] stderr:     rctx['ids'])
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/kivy/lang/builder.py", line 254, in create_handler
[WARNING] stderr:     cause=tb)
[WARNING] stderr: 
